
import { KPI, RepairOrder, RepairStatus, Conversation, Sale, Invoice, InvoiceType, Client, Appointment, SaleOrder, Product } from './types';

export const KPIS: KPI[] = [
  { label: 'Ventas Hoy', value: '$127.000', trend: 23, trendUp: true, icon: 'dollar' },
  { label: 'Reparaciones', value: '12 Activas', trend: 2, trendUp: false, icon: 'tool' },
  { label: 'Turnos Hoy', value: '5 Total', trend: 0, trendUp: true, icon: 'calendar' },
  { label: 'Mensajes', value: '8 Sin leer', trend: 5, trendUp: false, icon: 'message' },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Juan Pérez',
    phone: '+54 9 11 5678-9012',
    email: 'juan@gmail.com',
    type: 'Particular',
    origin: 'WhatsApp',
    totalSpent: 189000,
    repairsCount: 3,
    purchasesCount: 1,
    lastVisit: '2025-12-02',
    tags: ['VIP'],
    createdAt: '2024-06-15',
    activity: [
      { date: '2025-12-02', action: 'Reparación completada', detail: 'Cambio batería iPhone 13' },
      { date: '2025-11-15', action: 'Turno agendado', detail: 'Diagnóstico MacBook' },
    ]
  },
  {
    id: 'c2',
    name: 'María García',
    phone: '+54 9 11 4321-8765',
    email: 'maria@techsolutions.com',
    type: 'Empresa',
    origin: 'Google',
    totalSpent: 432000,
    repairsCount: 8,
    purchasesCount: 3,
    lastVisit: '2025-12-04',
    tags: ['Frecuente', 'Empresa'],
    createdAt: '2023-03-20',
    activity: [
      { date: '2025-12-04', action: 'Compra web', detail: '3x Fundas AirPods' },
      { date: '2025-12-01', action: 'Mensaje WhatsApp', detail: 'Consulta garantía' },
    ]
  },
  {
    id: 'c3',
    name: 'Carlos López',
    phone: '+54 9 11 9876-5432',
    email: 'carlos@yahoo.com',
    type: 'Particular',
    origin: 'Instagram',
    totalSpent: 45000,
    repairsCount: 1,
    purchasesCount: 0,
    lastVisit: '2025-11-20',
    tags: [],
    createdAt: '2025-11-20',
    activity: [
      { date: '2025-11-20', action: 'Primera visita', detail: 'Reparación pantalla iPad' },
    ]
  },
  {
    id: 'c4',
    name: 'Tech Solutions SA',
    phone: '+54 9 11 1234-5678',
    email: 'compras@techsolutions.com.ar',
    type: 'Empresa',
    origin: 'Referido',
    totalSpent: 1250000,
    repairsCount: 15,
    purchasesCount: 8,
    lastVisit: '2025-12-03',
    tags: ['VIP', 'Empresa', 'Mayorista'],
    createdAt: '2022-08-10',
    activity: [
      { date: '2025-12-03', action: 'Factura emitida', detail: 'Fact A 0001-00000087' },
      { date: '2025-12-01', action: 'Ingreso equipo', detail: '5 MacBooks para service' },
    ]
  },
  {
    id: 'c5',
    name: 'Roberto Sánchez',
    phone: '+54 9 11 5555-1234',
    email: 'roberto.s@hotmail.com',
    type: 'Particular',
    origin: 'Local',
    totalSpent: 78000,
    repairsCount: 2,
    purchasesCount: 1,
    lastVisit: '2025-10-15',
    tags: ['Moroso'],
    createdAt: '2024-02-28',
    activity: [
      { date: '2025-10-15', action: 'Deuda pendiente', detail: 'Reparación sin pagar $35.000' },
    ]
  },
];

export const MOCK_REPAIRS: RepairOrder[] = [
  {
    id: '#52',
    device: 'iPhone 13 Pro',
    issue: 'Cambio de Batería',
    client: MOCK_CLIENTS[0],
    status: RepairStatus.RECEIVED,
    cost: 40000,
    dateIn: '2025-12-04',
    dateOutEst: '2025-12-05'
  },
  {
    id: '#48',
    device: 'iPad Pro 11"',
    issue: 'Pantalla astillada',
    client: MOCK_CLIENTS[1],
    status: RepairStatus.DIAGNOSTIC,
    cost: 120000,
    dateIn: '2025-12-03',
    dateOutEst: '2025-12-06'
  },
  {
    id: '#45',
    device: 'MacBook Air M1',
    issue: 'No enciende',
    client: MOCK_CLIENTS[2],
    status: RepairStatus.REPAIRING,
    cost: 180000,
    dateIn: '2025-12-01',
    dateOutEst: '2025-12-07'
  }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: '1',
    clientName: 'Juan Pérez',
    lastMessage: 'Hola, quiero saber el precio del cambio de batería',
    timestamp: '10:23',
    unreadCount: 2,
    channel: 'whatsapp',
    status: 'urgent',
    messages: [
      { id: 'm1', sender: 'Juan Pérez', content: 'Hola', timestamp: '10:20', isMe: false, channel: 'whatsapp' },
      { id: 'm2', sender: 'Juan Pérez', content: 'Hola, quiero saber el precio del cambio de batería', timestamp: '10:23', isMe: false, channel: 'whatsapp' }
    ]
  },
  {
    id: '2',
    clientName: '@user_ig',
    lastMessage: 'Hacen envíos a Córdoba?',
    timestamp: '10:10',
    unreadCount: 1,
    channel: 'instagram',
    status: 'pending',
    messages: [
      { id: 'm3', sender: '@user_ig', content: 'Hacen envíos a Córdoba?', timestamp: '10:10', isMe: false, channel: 'instagram' }
    ]
  }
];

export const MOCK_SALES: Sale[] = [
  { id: '#50', date: 'Hoy', clientName: 'Juan Pérez', items: ['Film Like Paper', 'Funda AirPods'], total: 47000, status: 'Pending' },
  { id: '#49', date: 'Hoy', clientName: 'María García', items: ['Batería iPhone 13'], total: 60000, status: 'Shipped' },
  { id: '#48', date: 'Ayer', clientName: 'Carlos López', items: ['Cable USB-C'], total: 20000, status: 'Delivered' },
];

export const MOCK_INVOICES: Invoice[] = [
  { id: '1', number: '0001-00000087', type: InvoiceType.A, clientName: 'Tech Solutions SA', cuit: '30-71837199-2', amount: 125000, date: '2025-12-04', status: 'Pagada' },
  { id: '2', number: '0001-00000234', type: InvoiceType.B, clientName: 'Juan Pérez', cuit: '20-33445566-7', amount: 47000, date: '2025-12-04', status: 'Pendiente' },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt1',
    clientId: 'c1',
    clientName: 'Juan Pérez',
    phone: '+54 9 11 5678-9012',
    date: '2025-12-04',
    time: '10:00',
    duration: 30,
    type: 'Reparación',
    device: 'iPhone 13 Pro',
    service: 'Cambio de batería',
    status: 'Confirmado',
    notes: 'Cliente VIP, priorizar',
    notificationsSent: { confirmation: true, reminder24h: true, reminder2h: false }
  },
  {
    id: 'apt2',
    clientId: 'c2',
    clientName: 'María García',
    phone: '+54 9 11 4321-8765',
    date: '2025-12-04',
    time: '11:30',
    duration: 45,
    type: 'Diagnóstico',
    device: 'iPad Pro 11"',
    service: 'Diagnóstico pantalla',
    status: 'Pendiente',
    notificationsSent: { confirmation: true, reminder24h: false, reminder2h: false }
  },
  {
    id: 'apt3',
    clientId: 'c3',
    clientName: 'Carlos López',
    phone: '+54 9 11 9876-5432',
    date: '2025-12-04',
    time: '15:00',
    duration: 30,
    type: 'Entrega',
    device: 'MacBook Air M1',
    service: 'Entrega reparación',
    status: 'Cancelado',
    notes: 'Canceló por viaje',
    notificationsSent: { confirmation: true, reminder24h: true, reminder2h: true }
  },
  {
    id: 'apt4',
    clientId: 'c4',
    clientName: 'Tech Solutions SA',
    phone: '+54 9 11 1234-5678',
    date: '2025-12-04',
    time: '16:00',
    duration: 60,
    type: 'Entrega',
    device: 'MacBooks (5)',
    service: 'Entrega lote reparaciones',
    status: 'Confirmado',
    notificationsSent: { confirmation: true, reminder24h: true, reminder2h: false }
  },
  {
    id: 'apt5',
    clientId: 'c5',
    clientName: 'Roberto Sánchez',
    phone: '+54 9 11 5555-1234',
    date: '2025-12-04',
    time: '17:30',
    duration: 30,
    type: 'Presupuesto',
    device: 'iPhone 12',
    service: 'Presupuesto pantalla',
    status: 'Pendiente',
    notificationsSent: { confirmation: false, reminder24h: false, reminder2h: false }
  },
  {
    id: 'apt6',
    clientId: 'c1',
    clientName: 'Juan Pérez',
    phone: '+54 9 11 5678-9012',
    date: '2025-12-05',
    time: '09:00',
    duration: 30,
    type: 'Reparación',
    device: 'AirPods Pro',
    service: 'Cambio batería case',
    status: 'Confirmado',
    notificationsSent: { confirmation: true, reminder24h: false, reminder2h: false }
  },
];

export const MOCK_SALE_ORDERS: SaleOrder[] = [
  {
    id: '#50',
    clientId: 'c1',
    clientName: 'Juan Pérez',
    clientPhone: '+54 9 11 5678-9012',
    clientEmail: 'juan@gmail.com',
    items: [
      { productId: 'p1', name: 'Film Like Paper iPad Pro 11"', quantity: 1, unitPrice: 25000, subtotal: 25000 },
      { productId: 'p2', name: 'Funda AirPods Pro 2', quantity: 1, unitPrice: 22000, subtotal: 22000 },
    ],
    subtotal: 47000,
    discount: 0,
    shippingCost: 5500,
    total: 52500,
    status: 'Pendiente pago',
    paymentMethod: 'MercadoPago',
    paymentStatus: 'Pendiente',
    deliveryType: 'Envío domicilio',
    shippingAddress: 'Av. Corrientes 1234, CABA',
    createdAt: '2025-12-04T10:30:00',
    updatedAt: '2025-12-04T10:30:00',
  },
  {
    id: '#49',
    clientId: 'c2',
    clientName: 'María García',
    clientPhone: '+54 9 11 4321-8765',
    clientEmail: 'maria@techsolutions.com',
    items: [
      { productId: 'p3', name: 'Batería iPhone 13', quantity: 1, unitPrice: 55000, subtotal: 55000 },
    ],
    subtotal: 55000,
    discount: 0,
    shippingCost: 4500,
    total: 59500,
    status: 'Enviado',
    paymentMethod: 'MercadoPago',
    paymentStatus: 'Pagado',
    mercadoPagoId: 'MP-78291034',
    deliveryType: 'Envío domicilio',
    shippingAddress: 'Av. Santa Fe 2500, CABA',
    trackingNumber: 'AND-9182736450',
    trackingUrl: 'https://andreani.com/track/AND-9182736450',
    createdAt: '2025-12-03T15:20:00',
    updatedAt: '2025-12-04T09:15:00',
  },
  {
    id: '#48',
    clientId: 'c3',
    clientName: 'Carlos López',
    clientPhone: '+54 9 11 9876-5432',
    clientEmail: 'carlos@yahoo.com',
    items: [
      { productId: 'p4', name: 'Cable USB-C 2m', quantity: 2, unitPrice: 12000, subtotal: 24000 },
    ],
    subtotal: 24000,
    discount: 4000,
    shippingCost: 0,
    total: 20000,
    status: 'Entregado',
    paymentMethod: 'Efectivo',
    paymentStatus: 'Pagado',
    deliveryType: 'Retiro',
    createdAt: '2025-12-02T11:00:00',
    updatedAt: '2025-12-03T14:30:00',
  },
  {
    id: '#47',
    clientId: 'c4',
    clientName: 'Tech Solutions SA',
    clientPhone: '+54 9 11 1234-5678',
    clientEmail: 'compras@techsolutions.com.ar',
    items: [
      { productId: 'p5', name: 'Cargador MagSafe', quantity: 3, unitPrice: 45000, subtotal: 135000 },
      { productId: 'p6', name: 'Funda iPhone 15 Pro', quantity: 5, unitPrice: 18000, subtotal: 90000 },
    ],
    subtotal: 225000,
    discount: 11250, // 5% mayorista
    shippingCost: 0,
    total: 213750,
    status: 'Preparando',
    paymentMethod: 'Transferencia',
    paymentStatus: 'Pagado',
    deliveryType: 'Retiro',
    createdAt: '2025-12-04T08:45:00',
    updatedAt: '2025-12-04T11:00:00',
    notes: 'Cliente mayorista - Retira el viernes',
  },
  {
    id: '#46',
    clientId: 'c5',
    clientName: 'Roberto Sánchez',
    clientPhone: '+54 9 11 5555-1234',
    clientEmail: 'roberto.s@hotmail.com',
    items: [
      { productId: 'p7', name: 'Protector pantalla iPhone 14', quantity: 1, unitPrice: 15000, subtotal: 15000 },
    ],
    subtotal: 15000,
    discount: 0,
    shippingCost: 3500,
    total: 18500,
    status: 'Preparando',
    paymentMethod: 'MercadoPago',
    paymentStatus: 'Pagado',
    mercadoPagoId: 'MP-45678901',
    deliveryType: 'Envío sucursal',
    shippingAddress: 'Sucursal Correo Argentino - Belgrano',
    createdAt: '2025-12-04T09:00:00',
    updatedAt: '2025-12-04T10:00:00',
  },
  {
    id: '#45',
    clientId: 'c1',
    clientName: 'Juan Pérez',
    clientPhone: '+54 9 11 5678-9012',
    clientEmail: 'juan@gmail.com',
    items: [
      { productId: 'p8', name: 'AirPods Pro 2', quantity: 1, unitPrice: 320000, subtotal: 320000 },
    ],
    subtotal: 320000,
    discount: 0,
    shippingCost: 0,
    total: 320000,
    status: 'Cancelado',
    paymentMethod: 'MercadoPago',
    paymentStatus: 'Reembolsado',
    mercadoPagoId: 'MP-12340000',
    deliveryType: 'Retiro',
    createdAt: '2025-12-01T16:00:00',
    updatedAt: '2025-12-02T10:00:00',
    notes: 'Cliente canceló - cambió de opinión',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Batería iPhone 13 / 13 Mini',
    sku: 'BAT-IP13',
    description: 'Batería de reemplazo original compatible con iPhone 13 y 13 Mini. Capacidad 3227mAh.',
    type: 'Repuesto',
    category: 'Baterías',
    compatibleDevices: ['iPhone 13', 'iPhone 13 Mini'],
    costUSD: 12,
    costARS: 25000,
    priceARS: 55000,
    priceWithInstall: 65000,
    stock: 15,
    stockCommitted: 3,
    stockAvailable: 12,
    alertMin: 5,
    supplier: 'TechParts China',
    warrantyDays: 90,
    visibleWeb: true,
    featured: true,
    movements: [
      { id: 'm1', date: '2025-12-04', type: 'Uso reparación', quantity: -1, reference: 'REP-52' },
      { id: 'm2', date: '2025-12-03', type: 'Compra', quantity: 10, notes: 'Pedido #2341' },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2025-12-04',
  },
  {
    id: 'p2',
    name: 'Pantalla iPhone 14 Pro OLED',
    sku: 'PAN-IP14P',
    description: 'Display OLED original compatible iPhone 14 Pro. Incluye sensor Face ID.',
    type: 'Repuesto',
    category: 'Pantallas',
    compatibleDevices: ['iPhone 14 Pro'],
    costUSD: 85,
    costARS: 180000,
    priceARS: 350000,
    priceWithInstall: 380000,
    stock: 3,
    stockCommitted: 2,
    stockAvailable: 1,
    alertMin: 3,
    supplier: 'TechParts China',
    warrantyDays: 90,
    visibleWeb: false,
    featured: false,
    movements: [
      { id: 'm3', date: '2025-12-02', type: 'Uso reparación', quantity: -1, reference: 'REP-48' },
    ],
    createdAt: '2024-06-20',
    updatedAt: '2025-12-02',
  },
  {
    id: 'p3',
    name: 'Funda AirPods Pro 2 Silicona',
    sku: 'FUN-APP2',
    description: 'Funda protectora de silicona premium para AirPods Pro 2da gen.',
    type: 'Venta',
    category: 'Accesorios',
    compatibleDevices: ['AirPods Pro 2'],
    costARS: 8000,
    priceARS: 22000,
    stock: 28,
    stockCommitted: 0,
    stockAvailable: 28,
    alertMin: 10,
    supplier: 'Importadora BA',
    warrantyDays: 30,
    visibleWeb: true,
    featured: true,
    movements: [
      { id: 'm4', date: '2025-12-04', type: 'Venta', quantity: -1, reference: 'VTA-50' },
    ],
    createdAt: '2024-08-10',
    updatedAt: '2025-12-04',
  },
  {
    id: 'p4',
    name: 'Cable USB-C a Lightning 2m',
    sku: 'CAB-USCL2',
    description: 'Cable original Apple USB-C a Lightning, 2 metros.',
    type: 'Venta',
    category: 'Cables',
    compatibleDevices: ['iPhone', 'iPad', 'AirPods'],
    costARS: 5000,
    priceARS: 12000,
    stock: 45,
    stockCommitted: 2,
    stockAvailable: 43,
    alertMin: 15,
    supplier: 'Importadora BA',
    warrantyDays: 30,
    visibleWeb: true,
    featured: false,
    createdAt: '2024-03-05',
    updatedAt: '2025-12-03',
  },
  {
    id: 'p5',
    name: 'Film Like Paper iPad Pro 11"',
    sku: 'FLP-IPP11',
    description: 'Protector de pantalla textura papel para dibujo y escritura.',
    type: 'Venta',
    category: 'Protectores',
    compatibleDevices: ['iPad Pro 11 M1', 'iPad Pro 11 M2', 'iPad Air 4', 'iPad Air 5'],
    costARS: 10000,
    priceARS: 25000,
    priceWithInstall: 30000,
    stock: 12,
    stockCommitted: 0,
    stockAvailable: 12,
    alertMin: 5,
    supplier: 'Importadora BA',
    warrantyDays: 0,
    visibleWeb: true,
    featured: true,
    createdAt: '2024-09-01',
    updatedAt: '2025-11-28',
  },
  {
    id: 'p6',
    name: 'Cargador MagSafe Original',
    sku: 'CAR-MAG',
    description: 'Cargador inalámbrico MagSafe 15W original Apple.',
    type: 'Ambos',
    category: 'Cargadores',
    compatibleDevices: ['iPhone 12', 'iPhone 13', 'iPhone 14', 'iPhone 15'],
    costUSD: 20,
    costARS: 42000,
    priceARS: 85000,
    priceWithInstall: 90000,
    stock: 8,
    stockCommitted: 3,
    stockAvailable: 5,
    alertMin: 5,
    supplier: 'Apple Distribuidor',
    warrantyDays: 365,
    visibleWeb: true,
    featured: true,
    createdAt: '2024-02-20',
    updatedAt: '2025-12-01',
  },
  {
    id: 'p7',
    name: 'Batería MacBook Air M1',
    sku: 'BAT-MBA-M1',
    description: 'Batería de reemplazo para MacBook Air M1 2020.',
    type: 'Repuesto',
    category: 'Baterías',
    compatibleDevices: ['MacBook Air M1 2020'],
    costUSD: 45,
    costARS: 95000,
    priceARS: 180000,
    priceWithInstall: 210000,
    stock: 2,
    stockCommitted: 1,
    stockAvailable: 1,
    alertMin: 2,
    supplier: 'TechParts China',
    warrantyDays: 90,
    visibleWeb: false,
    featured: false,
    createdAt: '2024-05-15',
    updatedAt: '2025-12-04',
  },
  {
    id: 'p8',
    name: 'Protector Pantalla iPhone 15 Pro',
    sku: 'PRO-IP15P',
    description: 'Vidrio templado 9H para iPhone 15 Pro.',
    type: 'Ambos',
    category: 'Protectores',
    compatibleDevices: ['iPhone 15 Pro'],
    costARS: 3000,
    priceARS: 15000,
    priceWithInstall: 20000,
    stock: 0,
    stockCommitted: 0,
    stockAvailable: 0,
    alertMin: 10,
    supplier: 'Importadora BA',
    warrantyDays: 0,
    visibleWeb: false,
    featured: false,
    createdAt: '2024-10-01',
    updatedAt: '2025-11-20',
  },
];
